replicaCount: 1

image:
  repository: dgeorgievski/github-exporter
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.0.2"

prometheus:
  serviceMonitor:
    enabled: false
    namespace: monitoring

envVars:
  - name: GITHUB_TOKEN
    value: "Your GH API token here"
  - name: REPOS 
    value: "infinityworks/github-exporter"
  - name: PR_QUERY_OPTIONS
    value: "per_page=100&sort=long-running&direction=descending"