{
 "title": "GitHub",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "repo", "query": "label_values(repo)" }
  ]
 },
 "panels": [
  { "title": "$repo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "repo" },
  {
   "title": "Open Issues",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "github_repo_open_issues{repo=\"$repo\"} ",
     "legendFormat": "open issues"
    }
   ]
  },
  {
   "title": "Open Pull Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "github_repo_pull_request_count{repo=\"$repo\"} ",
     "legendFormat": "open prs"
    }
   ]
  },
  {
   "title": "Forks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "github_repo_forks{repo=\"$repo\"} ",
     "legendFormat": "forks"
    }
   ]
  },
  {
   "title": "Stars",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "github_repo_stars{repo=\"$repo\"} ",
     "legendFormat": "stars"
    }
   ]
  },
  { "title": "API Limits", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "type": "graph",
   "description": "The exporter uses the GitHub API to emit metrics, which has a rate limit. If this throttles, additional metrics will not be emitted.",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "github_rate_limit", "legendFormat": "Limit" },
    { "expr": "github_rate_remaining", "legendFormat": "Remaining" }
   ]
  },
  {
   "title": "Limit",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "github_rate_limit" }
   ]
  },
  {
   "title": "Remaining",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "github_rate_remaining" }
   ]
  }
 ]
}